(function(g){
'use strict';
const ROUND_SIZE=6, KEY='clockHeroProgressV1';
const LEVELS={easy:{minutes:[0]},medium:{minutes:[0,30]},challenge:{minutes:[0,5,10,15,20,25,30,35,40,45,50,55]}};
const STICKERS=[['⭐','キラキラぼし'],['🌈','にじ'],['🚀','ロケット'],['🦖','きょうりゅう'],['🐳','くじら'],['🦄','ユニコーン'],['🍓','いちご'],['👑','おうかん'],['🐙','たこ'],['🛸','UFO'],['🐼','パンダ'],['💎','ダイヤ']];
const core={
 handAngles:(h,m)=>({hour:(h%12)*30+m*.5,minute:m*6}),
 formatTime:(h,m)=>m===0?`${h}じ`:`${h}じ ${m}ふん`,
 digitalTime:(h,m)=>`${h}:${String(m).padStart(2,'0')}`,
 generateQuestion(level,prev,rnd=Math.random){const ms=(LEVELS[level]||LEVELS.easy).minutes;let h,m,key,n=0;do{h=1+Math.floor(rnd()*12);m=ms[Math.floor(rnd()*ms.length)];key=`${h}:${m}`;n++}while(key===prev&&n<12);return{hour:h,minute:m,key}},
 makeChoices(q,level){const out=new Set([this.formatTime(q.hour,q.minute)]),add=(h,m)=>out.add(this.formatTime(((h-1+12)%12)+1,m));if(level!=='easy'){const ms=LEVELS[level].minutes.filter(x=>x!==q.minute),near=ms.reduce((a,x)=>Math.abs(x-q.minute)<Math.abs(a-q.minute)?x:a,ms[0]);add(q.hour,near)}add(q.hour+1,q.minute);add(q.hour-1,q.minute);let m=level==='challenge'?(q.minute+15)%60:q.minute===0?30:0;while(out.size<3){add(q.hour+out.size,m);m=(m+10)%60}return[...out].slice(0,3)},
 starCount:n=>n>=6?3:n>=4?2:1
};
if(typeof module!=='undefined'&&module.exports)module.exports={core,LEVELS,STICKERS,ROUND_SIZE};
if(typeof document==='undefined')return;
const $=id=>document.getElementById(id), screens=['homeScreen','gameScreen','resultScreen','stickerScreen'];
const state={level:'easy',round:0,first:0,combo:0,max:0,prev:'',q:null,wrong:false,locked:false,sound:true};
let progress={stickers:[],bestCombo:0,plays:0};try{progress={...progress,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){ }
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(progress))}catch(_){}};
function show(id){screens.forEach(x=>$(x).classList.toggle('active',x===id));$('homeButton').classList.toggle('hidden',id==='homeScreen')}
function homeStats(){$('stickerCount').textContent=`${progress.stickers.length} / ${STICKERS.length}`;$('bestCombo').textContent=String(progress.bestCombo)}
function ticks(){const ns='http://www.w3.org/2000/svg',box=$('tickMarks');for(let i=0;i<60;i++){const l=document.createElementNS(ns,'line'),major=i%5===0;[['x1','100'],['y1',major?'18':'20'],['x2','100'],['y2',major?'29':'25'],['transform',`rotate(${i*6} 100 100)`],['class',major?'tick major':'tick']].forEach(([a,v])=>l.setAttribute(a,v));box.appendChild(l)}}
function setClock(h,m){const a=core.handAngles(h,m);$('hourHand').style.transform=`rotate(${a.hour}deg)`;$('minuteHand').style.transform=`rotate(${a.minute}deg)`}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function start(level){Object.assign(state,{level,round:0,first:0,combo:0,max:0,prev:'',locked:false});show('gameScreen');next()}
function next(){state.round++;state.wrong=false;state.locked=false;state.q=core.generateQuestion(state.level,state.prev);state.prev=state.q.key;$('roundLabel').textContent=`${state.round} / ${ROUND_SIZE}`;$('questionText').textContent=state.level==='easy'?'なんじ？':'なんじ なんぷん？';$('progressBar').style.width=`${(state.round-1)/ROUND_SIZE*100}%`;$('feedback').textContent='';$('feedback').className='feedback';$('hintBubble').classList.add('hidden');$('clockCard').classList.remove('correct-pop','wrong-shake');setClock(state.q.hour,state.q.minute);choices();hud()}
function choices(){const target=core.formatTime(state.q.hour,state.q.minute),grid=$('answerGrid');grid.innerHTML='';shuffle(core.makeChoices(state.q,state.level)).forEach(c=>{const b=document.createElement('button');b.type='button';b.className='answer-button';b.textContent=c;b.onclick=()=>answer(c,target,b);grid.appendChild(b)})}
function answer(c,target,b){if(state.locked)return;if(c===target){state.locked=true;if(!state.wrong)state.first++;state.combo++;state.max=Math.max(state.max,state.combo);b.classList.add('correct');document.querySelectorAll('.answer-button').forEach(x=>x.disabled=true);$('feedback').className='feedback good';$('feedback').textContent=`ピンポーン！ ${core.digitalTime(state.q.hour,state.q.minute)} ✨`;$('progressBar').style.width=`${state.round/ROUND_SIZE*100}%`;celebrate();successSound();speak();hud();setTimeout(()=>state.round>=ROUND_SIZE?finish():next(),720)}else{state.wrong=true;state.combo=0;b.disabled=true;b.classList.add('wrong');const card=$('clockCard');card.classList.remove('wrong-shake');void card.offsetWidth;card.classList.add('wrong-shake');$('feedback').className='feedback try';$('feedback').textContent='おしい！ もういちど 👀';$('hintBubble').textContent=state.q.minute===0?'ヒント：ながい はりが 12なら「◯じ ぴったり」だよ！':'ヒント：あおい ながい はりが「ぷん」、あかい みじかい はりが「じ」だよ！';$('hintBubble').classList.remove('hidden');trySound();hud()}}
function hud(){const n=Math.min(3,Math.floor((state.first+1)/2));$('comboText').textContent=String(state.combo);$('scoreStars').textContent='★'.repeat(n)+'☆'.repeat(3-n);$('scoreStars').setAttribute('aria-label',`ほし ${n}ぐ`)}
function celebrate(){const card=$('clockCard'),flash=$('flashLayer');card.classList.remove('correct-pop');void card.offsetWidth;card.classList.add('correct-pop');flash.classList.remove('go');void flash.offsetWidth;flash.classList.add('go');const layer=$('celebrationLayer'),colors=['#ff6b9f','#ffd93d','#6ee7b7','#74c0fc','#9b87f5','#ff8e53'],count=matchMedia('(prefers-reduced-motion: reduce)').matches?8:30;for(let i=0;i<count;i++){const p=document.createElement('i');p.className='confetti';p.style.left=`${Math.random()*100}%`;p.style.background=colors[i%colors.length];p.style.setProperty('--dur',`${700+Math.random()*600}ms`);p.style.setProperty('--drift',`${-80+Math.random()*160}px`);p.style.setProperty('--rot',`${Math.random()*180}deg`);layer.appendChild(p);setTimeout(()=>p.remove(),1450)}if(state.combo>=2){const d=document.createElement('div');d.className='combo-float';d.textContent=`${state.combo} コンボ！`;document.body.appendChild(d);setTimeout(()=>d.remove(),800)}if(navigator.vibrate)navigator.vibrate(25)}
let audio=null;function tone(f,t,d,v){if(!state.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),a=audio.createGain();o.frequency.value=f;a.gain.setValueAtTime(.001,audio.currentTime+t);a.gain.linearRampToValueAtTime(v,audio.currentTime+t+.01);a.gain.exponentialRampToValueAtTime(.001,audio.currentTime+t+d);o.connect(a).connect(audio.destination);o.start(audio.currentTime+t);o.stop(audio.currentTime+t+d+.03)}catch(_){}}
const successSound=()=>{tone(523,0,.13,.13);tone(659,.09,.14,.12);tone(state.combo>=3?1047:784,.18,.2,.11)},trySound=()=>{tone(300,0,.1,.06);tone(260,.08,.11,.05)};
function speak(){if(!state.sound||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(state.q.minute?`${state.q.hour}時${state.q.minute}分`:`${state.q.hour}時`);u.lang='ja-JP';u.rate=1.05;u.pitch=1.12;speechSynthesis.speak(u)}catch(_){}}
function reward(){const left=STICKERS.map((_,i)=>i).filter(i=>!progress.stickers.includes(i)),i=left.length?left[Math.floor(Math.random()*left.length)]:Math.floor(Math.random()*STICKERS.length);if(!progress.stickers.includes(i))progress.stickers.push(i);return STICKERS[i]}
function finish(){progress.plays=(progress.plays||0)+1;progress.bestCombo=Math.max(progress.bestCombo||0,state.max);const r=reward();save();homeStats();const stars=core.starCount(state.first);$('resultStars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('resultAccuracy').textContent=`${ROUND_SIZE}もんちゅう ${state.first}もん いっぱつせいかい！`;$('resultTitle').textContent=stars===3?'スーパー とけいヒーロー！':stars===2?'やったね！':'さいごまで できた！';$('resultMessage').textContent=stars===3?'ぜんぶ すごい！ つぎは べつの むずかしさも ためしてみよう。':'まちがえても だいじょうぶ。くりかえすほど とけいが すらすら よめるよ！';$('rewardSticker').textContent=r[0];$('rewardName').textContent=r[1];show('resultScreen');setTimeout(celebrate,80)}
function book(){const b=$('stickerBook');b.innerHTML='';STICKERS.forEach(([e,n],i)=>{const on=progress.stickers.includes(i),d=document.createElement('div');d.className=`sticker-slot${on?'':' locked'}`;d.innerHTML=`<span class="emoji">${on?e:'❔'}</span><span class="name">${on?n:'？？？'}</span>`;b.appendChild(d)})}
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>start(b.dataset.level));$('againButton').onclick=()=>start(state.level);$('changeLevelButton').onclick=$('homeButton').onclick=$('stickerBackButton').onclick=()=>{show('homeScreen');homeStats()};$('showStickersButton').onclick=()=>{book();show('stickerScreen')};$('soundButton').onclick=()=>{state.sound=!state.sound;$('soundButton').textContent=state.sound?'🔊':'🔇'};
ticks();homeStats();
})(typeof globalThis!=='undefined'?globalThis:this);
